### ISSUE TITLE
bad numerical issues

### ISSUE THREAD

**Issue by bomeara** [bomeara/BMhyb#2]
If the final VCV has any eigen values < 0 (or just tiny), it is not positive definite. Calculation of the likelihoods may have no relation to the truth. And this can happen for realistic values of our parameters. The spline smoothing is supposed to deal with this, but doesn't do it well. We can see if matrices are ultrametric (this does not mean the same as trees being ultrametric) but how do you get likelihood in a region that is biologically realistic but which isn't appropriate?

We've tried simulating, estimating a var() on the simulated tips to get the VCV, and then use that, but that often has issues as well. We implemented a pseudo-determinant: that also failed. We might do ABC, but it's embarrassing.

**Comment by bomeara** [comment]
This could underly our "bad" performance at param estimation: for many runs, the true param values are in areas where likelihood can't really be calculated.

**Comment by bomeara** [comment]
Maybe do map: show the area of parameter space where the true answer may lie, but due to numerical issues we can't see it. If you don't enter that region, then no worries

**Comment by djhwueng** [comment]
The log likelihood shall have range on R. We will rerun our analysis and check if the performance can be improved on parameter estimation.

**Comment by bomeara** [comment]
Idea from Daniel Caetano: Use Ho & Ane. See R/Caetano_Harmon_2017_pruning_algorithm.R for their example code.

**Comment by bomeara** [comment]
Believe we have it fixed, but checking.
